@startuml C4 Diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!$ICONURL = "https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons"
!include $ICONURL/common.puml
!include $ICONURL/devicons/java.puml
!include $ICONURL/devicons2/arduino.puml
!include $ICONURL/font-awesome-6/gear.puml

LAYOUT_LEFT_RIGHT()
Boundary(l1, "Camada de IoT e Física") {
    System_Ext(machine, "Injetora de Plástico", "A cada ciclo de produção, gera um sinal elétrico", $sprite="gear")
    System(microcontroller, "Microcontrolador", "Permite fazer contas", $sprite="arduino")
}

System_Boundary(l2, "Camada de Sistema Web") {
    System(backend, "API", "Permite fazer contas", $sprite="java")
}

Rel(machine, microcontroller, "Envia sinal elétrico")
Rel(microcontroller, backend, "Comunica recebimento do sinal - MQTT")
@enduml